-- MySQL Script generated by MySQL Workbench
-- Sat Jun 24 04:57:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `location` VARCHAR(100) NULL,
  `about_me` LONGTEXT NULL,
  `img_url` VARCHAR(2048) NULL,
  `img_back_url` VARCHAR(2048) NULL,
  `web_url` VARCHAR(2048) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `portfolio`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`education` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `institution` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `logo_url` VARCHAR(2048) NULL,
  `web_url` VARCHAR(2048) NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`),
  INDEX `fk_education_person1_idx` (`person_id` ASC) INVISIBLE,
  CONSTRAINT `fk_education_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `portfolio`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`experience` (
  `id` INT NOT NULL,
  `position` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `company` VARCHAR(255) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `logo_url` VARCHAR(2048) NULL,
  `web_url` VARCHAR(2048) NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`),
  INDEX `fk_experience_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_experience_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `portfolio`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`project` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `short_description` VARCHAR(100) NULL,
  `long_description` LONGTEXT NULL,
  `img_url` VARCHAR(2048) NULL,
  `web_url` VARCHAR(2048) NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`),
  INDEX `fk_project_person1_idx` (`person_id` ASC) INVISIBLE,
  CONSTRAINT `fk_project_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `portfolio`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`skill` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `level` INT NULL,
  `is_technical` TINYINT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`),
  INDEX `fk_skill_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_skill_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `portfolio`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`network` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `net_url` VARCHAR(2048) NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`),
  INDEX `fk_network_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_network_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `portfolio`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
